---
title:           Find Doctor Shopping
author:          Dennis Wollersheim and Stephen Callinan
date:            11.07.2018
linkcolor:       cyan
citecolor:       grey
output:
pdf_document:
  highlight:   zenburn
---

\tableofcontents

# motivation 

Get all 

```{r results='hide', message=FALSE, warning=FALSE}

intersect_filename = 'data/df_intersect.rda'
data_source_suffix='_rr'
data_source_suffix=''


source('lib/functions.R')
source( "lib/get_data.R")
# -------------------------------------------------



my_db_get_query ( paste0( " 
      select pin, spply_dt, pbs_code, pbs_rgltn24_adjst_qty as quantity
      from pbs", data_source_suffix, " 
      JOIN pbs_item pi USING (pbs_code) 
      WHERE pi.atc_code LIKE 'N02A%' ")) %>%
  as.tibble() %>% 
  { . } -> df_opioid

my_db_get_query ( paste0( " select * from patient", data_source_suffix)) %>%
  as.tibble() %>% 
  mutate( age = 2004 - yob , 
         age_group=cut( age, breaks=0:6*20 )) %>%
  { . } -> df_people


my_db_get_query ( paste0( " 
            select pin, date_of_service as spply_dt, spr, spr_rsp, rpr
            from mbs", data_source_suffix, " where item in (
                    select item
                    from mbs", data_source_suffix, " JOIN mbs_desc_latest USING (item)
                    where description like '%attendance%'
                    group by 1
                    order by count(*) desc
                    limit 20
            )")) %>%
  as.tibble() %>% 
  { . } -> df_mbs



if (file.exists( intersect_filename )) {
  load( intersect_filename, verbose=TRUE )
} else {
  #

  df_opioid %>%
    group_by(pin) %>%
    mutate( end_date = spply_dt + 7,
           start_date = spply_dt - 7) %>%
    select( pin, pbs_code, quantity, spply_dt, start_date, end_date) %>% 
    nest( pbs_code, spply_dt, start_date, end_date, quantity, .key=pbs ) %>%
    { . } -> df_pbs_nested

  #
  df_mbs %>%
    group_by(pin) %>%
    mutate( end_date = spply_dt + 7,
           start_date = spply_dt - 7) %>%
     select( pin, spr, spply_dt, start_date, end_date) %>% 
    nest( spr, spply_dt, start_date, end_date, .key=mbs ) %>%
    { . } -> df_mbs_nested
  #

  no_cores <- detectCores() - 1
  cluster <- create_cluster(no_cores)

  df_mbs_nested %>%
    inner_join( df_pbs_nested ) %>% 
    partition(pin, cluster=cluster )  %>%
    { . } -> df_both
  #
  cluster_library(df_both, c("tidyverse", "IRanges", "fuzzyjoin"))
  #

  df_both %>%
    do( joined = interval_inner_join( data.frame(.$mbs), 
                                     data.frame(.$pbs), 
                                     by=c('start_date','end_date') ))  %>%
  collect() %>%
  ungroup() %>%
  unnest() %>% 
  { . } -> df_intersect
#

save(df_intersect, file=intersect_filename)

}
```

# analysis - number of intersecting

```{r analysis}

df_intersect %>%
  count( pin, spr ) %>%
  count( pin, sort=TRUE ) %>%
  ggplot( aes( pin, nn ) ) + geom_col()


df_intersect %>%
  count(pin, sort=TRUE) 

df_intersect %>%
  count(pin, spr, sort=TRUE) 



df_intersect %>% 
  filter( pin=="06107781069")   

```
